### ISSUE TITLE
Use textures from mesh object

### ISSUE THREAD

**Issue by matriax** [matriax/Babylon3D#2]
The possibility to use/apply textures from the mesh objects of new creation. Or at least for the 0.5 do it for the cube/box. Will be very useful to create fast content for non 3D editor users, tutorials and templates to learn.

![textures_c2_objects](https://cloud.githubusercontent.com/assets/16635665/20836441/8b742d10-b89f-11e6-925f-830081c2bfb7.png)

So, only the ones you added in the right window will be applied. Or add all the map names and only apply the ones that have some image, i don't know if you can detect that.

Also this allow us to create various frames to get animated textures easily.

**Comment by X3MWorks** [comment]
Done

**Comment by matriax** [comment]
Damn! that was fast.

Before close the issue, only for the cube or are added for other new creation mesh objects? And the maps in the right side added all by default on object creation or we will have to create the maps we want to be applied? Any other info about this feature?

**Comment by X3MWorks** [comment]
Yes, I've posted some details on the Scirra thread

**Comment by matriax** [comment]
OHHH i see! Let here the link to the post and close this issue.
https://www.scirra.com/forum/babylon3d-for-construct-2-scene-loader-edition_p1083806?#p1083806
