### ISSUE TITLE
Add more default creation shapes

### ISSUE THREAD

**Issue by matriax** [matriax/Babylon3D#3]
Here is a list of possible new mesh creation:
- **Cone** (Can work for spikes)
- **Pyramid** (For low-poly spikes)
- **Hexagonal prism** (Columns)
- **Stairs** ( With 3 or 4 steps, i don't know if the steps numbers can be customized)

Perfect for items you have to collect
- **Regular octahedron**
- **Diamond** 
- **Star**

**Questions:** 
1.- We will have an unique mesh object on we have a list to select what kind of mesh we want to create, or for each one is a behaviour/plugin with their properties like radius, size, faces or whatever? 

2.- Each one appears with a default UVMAP reference to paint?

3.- In case they are too much, what is the hard thing? There are some kind of scripts in internet that generates that with some properties, or how? I'm interested on have a good resource of basic elements(fast prototyping), so will be great know how are done maybe i can help you.

**Extra:**
Also i don't know if this will be possible but an option to say how the geometry is generated, with quads or tris to give that low poly feel to some elements.

**Comment by X3MWorks** [comment]
I will only add the 5 basic shapes, those you've mentioned should be delayed.
1- List to select.
2- Yes.
3- What elements are you referring to ?
4- That can be already done with flatshading.

**Comment by matriax** [comment]
3.- I mean this:
![new_geometry](https://cloud.githubusercontent.com/assets/16635665/20851946/88d76524-b8e3-11e6-8d24-a6ab5f0cc5f9.png)

I don't know how exactly they are done/generated in real time. There is some way that create the 3D mesh procedurally, or "simply" you create the mesh in high poly in 3Dmax and in c2 you add the geometry/vectors numbers with the options to make it with less faces, subdivisions or whatever?

The idea is have some resource pack of lots of geometric things, but in that case maybe a list in properties not be the best way. Well, forgot at the moment, after the 0.5 i will see if i can do it myself in some way.

---


4.- About quads & tris i'm not refer to materials i mean this:
Quads: 
[](http://www.pumpkinheadlabs.com/wp-content/uploads/2016/03/little_guy_tree.png)

Tris: 
[](https://i.ytimg.com/vi/c3x9Y3TfXiw/maxresdefault.jpg)
[](https://dribbble.com/shots/217503-Poly-Tree/attachments/4919)
